name = "AdaptiveFlows"
uuid = "24d2106d-e7e1-4641-aa0a-4a5934943aa1"
version = "0.1.0"

[deps]
AffineMaps = "2c83c9a8-abf5-4329-a0d7-deffaf474661"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ChangesOfVariables = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
HeterogeneousComputing = "2182be2a-124f-4a91-8389-f06db5907a21"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MonotonicSplines = "568f7cb4-8305-41bc-b90d-d32b39cc99d1"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
ValueShapes = "136a8f8c-c49b-4edb-8b98-f3d64d48be8f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AffineMaps = "0.1, 0.2"
ArgCheck = "2"
ArraysOfArrays = "0.5.1, 0.6"
ChangesOfVariables = "0.1.3"
FunctionChains = "0.1"
Functors = "0.2, 0.3, 0.4"
HeterogeneousComputing = "0.1, 0.2"
InverseFunctions = "0.1"
Lux = "0.5"
MonotonicSplines = "0.1"
Optimisers = "0.2, 0.3"
StatsFuns = "1"
ValueShapes = "0.8.3, 0.9, 0.10"
Zygote = "0.6"
julia = "1.6"
